<a href="https://colab.research.google.com/github/maggiemcc02/HessianMonitorWork/blob/main/Cleaned_Absolute_Value_Matrix.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Introduction


In this notebook I work on implementing the absolute value of a matrix. This is needed for my 2D Hessian Monitor Function

In [ ]:
import numpy as np
import scipy.linalg as sci
import sympy as sp

# Algebraic Work


In [ ]:
# define a 2x2 symmetric matrix

a, b, c = sp.symbols('a b c')
A = sp.Matrix([[a, c], [c, b]])
A

Matrix([
[a, c],
[c, b]])

In [ ]:
# show it is symmetric

sp.transpose(A)

Matrix([
[a, c],
[c, b]])

In [ ]:
# find the eigenvalues

L1, L2, = A.eigenvals()

# This matches my algebraic work!

L1

a/2 + b/2 - sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2

In [ ]:
v1, v2 = A.eigenvects()

v1

# matches my workings (other option for v)

(a/2 + b/2 - sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2,
 1,
 [Matrix([
  [-b/c + (a/2 + b/2 - sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2)/c],
  [                                                          1]])])

In [ ]:
# fine the eigenvectors

Q, L = A.diagonalize()

Q # same result as what I have except they took free variable = 1

Matrix([
[(a - b - sqrt(a**2 - 2*a*b + b**2 + 4*c**2))/(2*c), (a - b + sqrt(a**2 - 2*a*b + b**2 + 4*c**2))/(2*c)],
[                                                 1,                                                  1]])

In [ ]:
L

Matrix([
[a/2 + b/2 - sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2,                                                0],
[                                               0, a/2 + b/2 + sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2]])

In [ ]:
# Plug in values
Q.subs(a, 1)

Matrix([
[(-b - sqrt(b**2 - 2*b + 4*c**2 + 1) + 1)/(2*c), (-b + sqrt(b**2 - 2*b + 4*c**2 + 1) + 1)/(2*c)],
[                                             1,                                              1]])

In [ ]:
Abs_L = sp.Abs(L)

Abs_L

Matrix([
[Abs(a/2 + b/2 - sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2),                                                     0],
[                                                    0, Abs(a/2 + b/2 + sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2)]])

In [ ]:
Q_inv = Q.inv()

Q_inv

Matrix([
[-c/sqrt(a**2 - 2*a*b + b**2 + 4*c**2),  (a - b + sqrt(a**2 - 2*a*b + b**2 + 4*c**2))/(2*sqrt(a**2 - 2*a*b + b**2 + 4*c**2))],
[ c/sqrt(a**2 - 2*a*b + b**2 + 4*c**2), (-a + b + sqrt(a**2 - 2*a*b + b**2 + 4*c**2))/(2*sqrt(a**2 - 2*a*b + b**2 + 4*c**2))]])

In [ ]:
abs_A = Q * Abs_L * Q.inv()

abs_A

Matrix([
[-(a - b - sqrt(a**2 - 2*a*b + b**2 + 4*c**2))*Abs(a/2 + b/2 - sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2)/(2*sqrt(a**2 - 2*a*b + b**2 + 4*c**2)) + (a - b + sqrt(a**2 - 2*a*b + b**2 + 4*c**2))*Abs(a/2 + b/2 + sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2)/(2*sqrt(a**2 - 2*a*b + b**2 + 4*c**2)), (-a + b + sqrt(a**2 - 2*a*b + b**2 + 4*c**2))*(a - b + sqrt(a**2 - 2*a*b + b**2 + 4*c**2))*Abs(a/2 + b/2 + sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2)/(4*c*sqrt(a**2 - 2*a*b + b**2 + 4*c**2)) + (a - b - sqrt(a**2 - 2*a*b + b**2 + 4*c**2))*(a - b + sqrt(a**2 - 2*a*b + b**2 + 4*c**2))*Abs(a/2 + b/2 - sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2)/(4*c*sqrt(a**2 - 2*a*b + b**2 + 4*c**2))],
[                                                                                              -c*Abs(a/2 + b/2 - sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2)/sqrt(a**2 - 2*a*b + b**2 + 4*c**2) + c*Abs(a/2 + b/2 + sqrt(a**2 - 2*a*b + b**2 + 4*c**2)/2)/sqrt(a**2 - 2*a*b + b**2 + 4*c**2),                                                       

# Numerical Work

In [ ]:
A = np.array([[1, 2], [2, 4]])

A

array([[1, 2],
       [2, 4]])

In [ ]:
# find its eigenvalues and eigenvectors

eigvals, eigvects = np.linalg.eig(A)

eigvects

array([[-0.89442719, -0.4472136 ],
       [ 0.4472136 , -0.89442719]])

In [ ]:
# create the parts of the diagonalization of A

Q = eigvects
Q_inv = np.linalg.inv(Q)

D = np.diag(eigvals)

print(Q)
print()
print(Q_inv)
print()
print(D)

[[-0.89442719 -0.4472136 ]
 [ 0.4472136  -0.89442719]]

[[-0.89442719  0.4472136 ]
 [-0.4472136  -0.89442719]]

[[0. 0.]
 [0. 5.]]


In [ ]:
# check the diagonalization

A_approx = Q @ D @ Q_inv

A_approx

array([[1., 2.],
       [2., 4.]])

In [ ]:
# compute the absolute value of A

abs_D = np.abs(D)

A_abs = Q @ abs_D @ Q_inv

A_abs

array([[1., 2.],
       [2., 4.]])

In [ ]:
# let's check my formulas

a = 1
b = 4
c = 2



# eigenvalues

L1 = ( (a+b) - np.sqrt( (a-b)**2 + 4*c**2 )) / 2
L2 = ( (a+b) + np.sqrt( (a-b)**2 + 4*c**2 )) / 2




# eigenvectors (normalized)

sc1 = 1 / (np.sqrt( c**2 + (L1 - a)**2 ))
vect1 = np.array([c, L1 - a])
v1 = sc1 * vect1

sc2 = 1 / (np.sqrt( c**2 + (L2 - a)**2 ))
vect2 = np.array([c, L2 - a])
v2 = sc2 * vect2



print('Eigenvalues and their Eigenvectors')
print()
print("λ1 =", L1, "with eigenvector : ", v1)
print()
print("λ2 =", L2, "with eigenvector : ", v2)


Eigenvalues and their Eigenvectors

λ1 = 0.0 with eigenvector :  [ 0.89442719 -0.4472136 ]

λ2 = 5.0 with eigenvector :  [0.4472136  0.89442719]
